---
kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm run test
  - name: notify
    image: plugins/slack
    settings:
      channel: react-ci-cd-jdflament
      webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
