---
kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: tests
    image: node:alpine
    commands:
      - npm run test
  - name: release
    image: plugins/github-release
    commands:
      - tar -zcvf build.tar.gz build/
    settings:
      api_key:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag
  - name: notify
    image: plugins/slack
    settings:
      username: Drone
      icon_url: https://avatars0.githubusercontent.com/u/2181346?s=400&v=4
      channel: react-ci-cd-jdflament
      webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
